---
- name: "Systemd | {{ systemd_user }} | {{ systemd_type.key }} | Process Systemd Unit types"
  ansible.builtin.include_tasks: 
    file: "unit.yaml"
    apply:
      become_user: "{{ systemd_user }}"
      become: true
  vars:
    unit: "{{ systemd_unit.value }}"
    unit_file_path: "{% if systemd_unit.value.options.filepath is defined %}{{ systemd_unit.value.options.filepath }}{% else %}{{ systemd_path }}/{{ systemd_unit.key }}.{{ systemd_type.key }}{% endif %}"
  loop: "{{ systemd_type.value | dict2items }}"
  loop_control:
    loop_var: systemd_unit